name: kamel_pro
description: "KAMEL PRO IPTV - Android TV App"
publish_to: 'none'
version: 1.0.125+125  # 👈 بدّل 124 بـ 125

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  wakelock_plus: ^1.2.0
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  font_awesome_flutter: 10.4.0
  device_info_plus: ^10.1.0
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  supabase_flutter: ^2.5.0
  flutter_internet_speed_test: ^1.5.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpeg
    - assets/logo.png
    - assets/avatar.png
    - assets/live.png
    - assets/filmes.png
    - assets/series.png
    - assets/favorites.png
    - assets/ajustes.png
    - assets/globe.png
    - assets/qr.png
    - assets/update.png
    - assets/speed.png
    - assets/qr_big.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/avatar.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/avatar.png"
