import 'package:shared_preferences/shared_preferences.dart';

class Lang {
  static String current = 'ar';
  static Map<String, Map<String, String>> t = {
    'ar': {
      'live': 'مباشر',
      'movies': 'أفلام',
      'series': 'مسلسلات',
      'epg': 'الدليل',
      'fav': 'المفضلة',
      'settings': 'الإعدادات',
      'all': 'الكل',
      'categories': 'الباقات',
      'added': 'أضيف للمفضلة',
      'removed': 'حذف من المفضلة',
      'lang': 'اللغة',
      'player': 'المشغل',
      'logout_title': 'تسجيل الخروج',
      'logout_msg': 'هل تريد تسجيل الخروج من الحساب؟',
      'yes': 'نعم',
      'no': 'لا',
      'fav_title': 'القنوات المفضلة',
      'no_fav': 'ما فماش قنوات مفضلة',
      'channel': 'قناة',
      'channels': 'القنوات',
      'ajouter_liste': 'إضافة قائمة',
      'parental': 'التحكم الأبوي',
      'changer_liste': 'تغيير القائمة',
      'changer_langue': 'تغيير اللغة',
      'disposition': 'تغيير العرض',
      'masquer_live': 'إخفاء المباشر',
      'masquer_vod': 'إخفاء الأفلام',
      'masquer_series': 'إخفاء المسلسلات',
      'clear_history': 'مسح السجل',
      'effacer_films': 'مسح الأفلام',
      'effacer_series': 'مسح المسلسلات',
      'tri_chaines': 'ترتيب القنوات',
      'live_format': 'صيغة البث',
      'select_player': 'اختيار المشغل',
      'acteurs_externes': 'مشغلات خارجية',
      'mise_a_jour': 'تحديث الآن',
      'choisir_langue': 'اختر اللغة',
      'bientot': 'قريباً...',
      'qr_code': 'رمز QR',
      'speed_test': 'اختبار سرعة الانترنات',
      // النصوص الجديدة اللي ناقصة
      'search_channel': 'بحث عن قناة...',
      'search_movie': 'بحث عن فيلم...',
      'search_series': 'بحث عن مسلسل...',
      'days_left': 'يوم',
      'ramadan': 'رمضان 2026',
      'turkish_sub': 'يعرض الان تركي مترجم',
      'turkish_dub': 'يعرض الان تركي مدبلج',
    },
    'fr': {
      'live': 'DIRECT',
      'movies': 'FILMS',
      'series': 'SÉRIES',
      'epg': 'GUIDE',
      'fav': 'FAVORIS',
      'settings': 'PARAMÈTRES',
      'all': 'Tout',
      'categories': 'Catégories',
      'added': 'Ajouté aux favoris',
      'removed': 'Retiré',
      'lang': 'Langue',
      'player': 'Lecteur',
      'logout_title': 'Déconnexion',
      'logout_msg': 'Voulez-vous vous déconnecter?',
      'yes': 'Oui',
      'no': 'Non',
      'fav_title': 'Chaînes favorites',
      'no_fav': 'Aucune chaîne favorite',
      'channel': 'Chaîne',
      'channels': 'Chaînes',
      'ajouter_liste': 'Ajouter une liste',
      'parental': 'Contrôle parental',
      'changer_liste': 'Changer de liste',
      'changer_langue': 'Changer de langue',
      'disposition': 'Changer la disposition',
      'masquer_live': 'Masquer live',
      'masquer_vod': 'Masquer VOD',
      'masquer_series': 'Masquer séries',
      'clear_history': 'Clear History',
      'effacer_films': 'Effacer films',
      'effacer_series': 'Effacer séries',
      'tri_chaines': 'Tri des chaînes',
      'live_format': 'Live Stream Format',
      'select_player': 'Select Player',
      'acteurs_externes': 'Acteurs externes',
      'mise_a_jour': 'Mettre à jour',
      'choisir_langue': 'Choisir la langue',
      'bientot': 'Bientôt...',
      'qr_code': 'Code QR',
      'speed_test': 'Test vitesse',
      // النصوص الجديدة
      'search_channel': 'Rechercher une chaîne...',
      'search_movie': 'Rechercher un film...',
      'search_series': 'Rechercher une série...',
      'days_left': 'jours',
      'ramadan': 'Ramadan 2026',
      'turkish_sub': 'Turc sous-titré en cours',
      'turkish_dub': 'Turc doublé en cours',
    },
    'cs': {
      'live': 'ŽIVĚ',
      'movies': 'FILMY',
      'series': 'SERIÁLY',
      'epg': 'PROGRAM',
      'fav': 'OBLÍBENÉ',
      'settings': 'NASTAVENÍ',
      'all': 'Vše',
      'categories': 'Kategorie',
      'added': 'Přidáno',
      'removed': 'Odebráno',
      'lang': 'Jazyk',
      'player': 'Přehrávač',
      'logout_title': 'Odhlásit se',
      'logout_msg': 'Chcete se odhlásit?',
      'yes': 'Ano',
      'no': 'Ne',
      'fav_title': 'Oblíbené kanály',
      'no_fav': 'Žádné oblíbené kanály',
      'channel': 'Kanál',
      'channels': 'Kanály',
      'ajouter_liste': 'Přidat seznam',
      'parental': 'Rodičovská kontrola',
      'changer_liste': 'Změnit seznam',
      'changer_langue': 'Změnit jazyk',
      'disposition': 'Změnit rozložení',
      'masquer_live': 'Skrýt živě',
      'masquer_vod': 'Skrýt VOD',
      'masquer_series': 'Skrýt seriály',
      'clear_history': 'Vymazat historii',
      'effacer_films': 'Smazat filmy',
      'effacer_series': 'Smazat seriály',
      'tri_chaines': 'Třídění kanálů',
      'live_format': 'Formát streamu',
      'select_player': 'Vybrat přehrávač',
      'acteurs_externes': 'Externí',
      'mise_a_jour': 'Aktualizovat',
      'choisir_langue': 'Vyberte jazyk',
      'bientot': 'Již brzy...',
      'qr_code': 'QR kód',
      'speed_test': 'Test rychlosti',
      // النصوص الجديدة
      'search_channel': 'Hledat kanál...',
      'search_movie': 'Hledat film...',
      'search_series': 'Hledat seriál...',
      'days_left': 'dní',
      'ramadan': 'Ramadán 2026',
      'turkish_sub': 'Turecký s titulky',
      'turkish_dub': 'Turecký dabing',
    },
    'en': {
      'live': 'LIVE',
      'movies': 'MOVIES',
      'series': 'SERIES',
      'epg': 'GUIDE',
      'fav': 'FAVORITES',
      'settings': 'SETTINGS',
      'all': 'All',
      'categories': 'Categories',
      'added': 'Added to favorites',
      'removed': 'Removed',
      'lang': 'Language',
      'player': 'Player',
      'logout_title': 'Logout',
      'logout_msg': 'Do you want to logout?',
      'yes': 'Yes',
      'no': 'No',
      'fav_title': 'Favorite channels',
      'no_fav': 'No favorite channels',
      'channel': 'Channel',
      'channels': 'Channels',
      'ajouter_liste': 'Add list',
      'parental': 'Parental control',
      'changer_liste': 'Change list',
      'changer_langue': 'Change language',
      'disposition': 'Change layout',
      'masquer_live': 'Hide live',
      'masquer_vod': 'Hide VOD',
      'masquer_series': 'Hide series',
      'clear_history': 'Clear history',
      'effacer_films': 'Clear movies',
      'effacer_series': 'Clear series',
      'tri_chaines': 'Sort channels',
      'live_format': 'Live Stream Format',
      'select_player': 'Select Player',
      'acteurs_externes': 'External players',
      'mise_a_jour': 'Update now',
      'choisir_langue': 'Choose language',
      'bientot': 'Coming soon...',
      'qr_code': 'QR Code',
      'speed_test': 'Speed Test',
      // النصوص الجديدة
      'search_channel': 'Search channel...',
      'search_movie': 'Search movie...',
      'search_series': 'Search series...',
      'days_left': 'days',
      'ramadan': 'Ramadan 2026',
      'turkish_sub': 'Turkish subtitled',
      'turkish_dub': 'Turkish dubbed',
    },
    'de': {
      'live': 'LIVE',
      'movies': 'FILME',
      'series': 'SERIEN',
      'epg': 'PROGRAMM',
      'fav': 'FAVORITEN',
      'settings': 'EINSTELLUNGEN',
      'all': 'Alle',
      'categories': 'Kategorien',
      'added': 'Zu Favoriten hinzugefügt',
      'removed': 'Entfernt',
      'lang': 'Sprache',
      'player': 'Player',
      'logout_title': 'Abmelden',
      'logout_msg': 'Möchten Sie sich abmelden?',
      'yes': 'Ja',
      'no': 'Nein',
      'fav_title': 'Lieblingskanäle',
      'no_fav': 'Keine Lieblingskanäle',
      'channel': 'Kanal',
      'channels': 'Kanäle',
      'ajouter_liste': 'Liste hinzufügen',
      'parental': 'Kindersicherung',
      'changer_liste': 'Liste ändern',
      'changer_langue': 'Sprache ändern',
      'disposition': 'Layout ändern',
      'masquer_live': 'Live ausblenden',
      'masquer_vod': 'VOD ausblenden',
      'masquer_series': 'Serien ausblenden',
      'clear_history': 'Verlauf löschen',
      'effacer_films': 'Filme löschen',
      'effacer_series': 'Serien löschen',
      'tri_chaines': 'Kanäle sortieren',
      'live_format': 'Live-Stream-Format',
      'select_player': 'Player auswählen',
      'acteurs_externes': 'Externe Player',
      'mise_a_jour': 'Jetzt aktualisieren',
      'choisir_langue': 'Sprache wählen',
      'bientot': 'Bald verfügbar...',
      'qr_code': 'QR-Code',
      'speed_test': 'Speedtest',
      // النصوص الجديدة
      'search_channel': 'Kanal suchen...',
      'search_movie': 'Film suchen...',
      'search_series': 'Serie suchen...',
      'days_left': 'Tage',
      'ramadan': 'Ramadan 2026',
      'turkish_sub': 'Türkisch mit Untertiteln',
      'turkish_dub': 'Türkisch synchronisiert',
    },
  };

  static String get(String key) => t[current]![key]?? key;

  static Future load() async {
    final p = await SharedPreferences.getInstance();
    current = p.getString('lang')?? 'ar';
  }

  static Future set(String l) async {
    current = l;
    final p = await SharedPreferences.getInstance();
    await p.setString('lang', l);
  }
}
