import 'package:shared_preferences/shared_preferences.dart';

class Lang {
  static String current = 'ar';
  static Map<String, Map<String, String>> t = {
    'ar': {
      'live': 'مباشر',
      'movies': 'أفلام',
      'series': 'مسلسلات',
      'epg': 'الدليل',
      'fav': 'المفضلة',
      'settings': 'الإعدادات',
      'all': 'الكل',
      'categories': 'الباقات',
      'added': 'أضيف للمفضلة',
      'removed': 'حذف من المفضلة',
      'lang': 'اللغة',
      'player': 'المشغل',
      'logout_title': 'تسجيل الخروج',
      'logout_msg': 'هل تريد تسجيل الخروج من الحساب؟',
      'yes': 'نعم',
      'no': 'لا',
      'fav_title': 'القنوات المفضلة',
      'no_fav': 'ما فماش قنوات مفضلة',
      'channel': 'قناة',
      'channels': 'القنوات',
      // --- Paramètres جديد ---
      'ajouter_liste': 'إضافة قائمة',
      'parental': 'التحكم الأبوي',
      'changer_liste': 'تغيير القائمة',
      'changer_langue': 'تغيير اللغة',
      'disposition': 'تغيير العرض',
      'masquer_live': 'إخفاء المباشر',
      'masquer_vod': 'إخفاء الأفلام',
      'masquer_series': 'إخفاء المسلسلات',
      'clear_history': 'مسح السجل',
      'effacer_films': 'مسح الأفلام',
      'effacer_series': 'مسح المسلسلات',
      'tri_chaines': 'ترتيب القنوات',
      'live_format': 'صيغة البث',
      'select_player': 'اختيار المشغل',
      'acteurs_externes': 'مشغلات خارجية',
      'mise_a_jour': 'تحديث الآن',
      'choisir_langue': 'اختر اللغة',
      'bientot': 'قريباً...',
    },
    'fr': {
      'live': 'DIRECT',
      'movies': 'FILMS',
      'series': 'SÉRIES',
      'epg': 'GUIDE',
      'fav': 'FAVORIS',
      'settings': 'PARAMÈTRES',
      'all': 'Tout',
      'categories': 'Catégories',
      'added': 'Ajouté aux favoris',
      'removed': 'Retiré',
      'lang': 'Langue',
      'player': 'Lecteur',
      'logout_title': 'Déconnexion',
      'logout_msg': 'Voulez-vous vous déconnecter?',
      'yes': 'Oui',
      'no': 'Non',
      'fav_title': 'Chaînes favorites',
      'no_fav': 'Aucune chaîne favorite',
      'channel': 'Chaîne',
      'channels': 'Chaînes',
      // --- Paramètres ---
      'ajouter_liste': 'Ajouter une liste',
      'parental': 'Contrôle parental',
      'changer_liste': 'Changer de liste',
      'changer_langue': 'Changer de langue',
      'disposition': 'Changer la disposition',
      'masquer_live': 'Masquer live',
      'masquer_vod': 'Masquer VOD',
      'masquer_series': 'Masquer séries',
      'clear_history': 'Clear History',
      'effacer_films': 'Effacer films',
      'effacer_series': 'Effacer séries',
      'tri_chaines': 'Tri des chaînes',
      'live_format': 'Live Stream Format',
      'select_player': 'Select Player',
      'acteurs_externes': 'Acteurs externes',
      'mise_a_jour': 'Mettre à jour',
      'choisir_langue': 'Choisir la langue',
      'bientot': 'Bientôt...',
    },
    'cs': {
      'live': 'ŽIVĚ',
      'movies': 'FILMY',
      'series': 'SERIÁLY',
      'epg': 'PROGRAM',
      'fav': 'OBLÍBENÉ',
      'settings': 'NASTAVENÍ',
      'all': 'Vše',
      'categories': 'Kategorie',
      'added': 'Přidáno',
      'removed': 'Odebráno',
      'lang': 'Jazyk',
      'player': 'Přehrávač',
      'logout_title': 'Odhlásit se',
      'logout_msg': 'Chcete se odhlásit?',
      'yes': 'Ano',
      'no': 'Ne',
      'fav_title': 'Oblíbené kanály',
      'no_fav': 'Žádné oblíbené kanály',
      'channel': 'Kanál',
      'channels': 'Kanály',
      // --- Paramètres ---
      'ajouter_liste': 'Přidat seznam',
      'parental': 'Rodičovská kontrola',
      'changer_liste': 'Změnit seznam',
      'changer_langue': 'Změnit jazyk',
      'disposition': 'Změnit rozložení',
      'masquer_live': 'Skrýt živě',
      'masquer_vod': 'Skrýt VOD',
      'masquer_series': 'Skrýt seriály',
      'clear_history': 'Vymazat historii',
      'effacer_films': 'Smazat filmy',
      'effacer_series': 'Smazat seriály',
      'tri_chaines': 'Třídění kanálů',
      'live_format': 'Formát streamu',
      'select_player': 'Vybrat přehrávač',
      'acteurs_externes': 'Externí',
      'mise_a_jour': 'Aktualizovat',
      'choisir_langue': 'Vyberte jazyk',
      'bientot': 'Již brzy...',
    },
  };

  static String get(String key) => t[current]![key]?? key;

  static Future load() async {
    final p = await SharedPreferences.getInstance();
    current = p.getString('lang')?? 'ar';
  }

  static Future set(String l) async {
    current = l;
    final p = await SharedPreferences.getInstance();
    await p.setString('lang', l);
  }
}
