import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'player.dart';

class SeriesScreen extends StatefulWidget { @override _SeriesScreenState createState()=>_SeriesScreenState(); }
class _SeriesScreenState extends State<SeriesScreen>{
  List series=[]; List cats=[]; String sel='All'; bool loading=true;
  @override void initState(){super.initState();_load();}
  _load() async{final p=await SharedPreferences.getInstance();String s=(p.getString('server')??'').replaceAll(RegExp(r'/$'),'');String u=p.getString('username')??'';String pw=p.getString('password')??'';try{final c=await http.get(Uri.parse('$s/player_api.php?username=$u&password=$pw&action=get_series_categories')).timeout(Duration(seconds:15));final se=await http.get(Uri.parse('$s/player_api.php?username=$u&password=$pw&action=get_series')).timeout(Duration(seconds:20));if(c.statusCode==200)cats=json.decode(c.body);if(se.statusCode==200)series=json.decode(se.body);}catch(_){}setState(()=>loading=false);}
  @override Widget build(BuildContext c){final f=sel=='All'?series:series.where((e)=>e['category_id'].toString()==sel).toList();return Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.transparent,title:Text('SERIES')),body:loading?Center(child:CircularProgressIndicator(color:Colors.orange)):Column(children:[Container(height:48,child:ListView(scrollDirection:Axis.horizontal,padding:EdgeInsets.symmetric(horizontal:8),children:[_cat('All','الكل'),...cats.map((x)=>_cat(x['category_id'].toString(),x['category_name']))])),Expanded(child:GridView.builder(padding:EdgeInsets.all(14),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:6,childAspectRatio:.68,mainAxisSpacing:12,crossAxisSpacing:12),itemCount:f.length,itemBuilder:(_,i){final s=f[i];return Focus(autofocus:i==0,child:Builder(builder:(ctx){final fo=Focus.of(ctx).hasFocus;return GestureDetector(onTap:()=>_open(s),child:AnimatedContainer(duration:Duration(milliseconds:120),decoration:BoxDecoration(border:Border.all(color:fo?Colors.orange:Colors.transparent,width:3),borderRadius:BorderRadius.circular(8)),child:Column(children:[Expanded(child:ClipRRect(borderRadius:BorderRadius.circular(6),child:s['cover']!=null?Image.network(s['cover'],fit:BoxFit.cover,width:double.infinity,errorBuilder:(_,__,___)=>Container(color:Colors.grey[900],child:Icon(Icons.tv,size:40))):Container(color:Colors.grey[900],child:Icon(Icons.tv,size:40)))),SizedBox(height:4),Text(s['name']??'',maxLines:2,overflow:TextOverflow.ellipsis,textAlign:TextAlign.center,style:TextStyle(color:Colors.white,fontSize:11))]));}));}))]));}
  Widget _cat(id,name){final a=sel==id;return Padding(padding:EdgeInsets.symmetric(horizontal:4),child:Focus(child:Builder(builder:(ctx){final fo=Focus.of(ctx).hasFocus;return ChoiceChip(label:Text(name),selected:a,selectedColor:Colors.orange,backgroundColor:fo?Colors.white24:Colors.grey[800],onSelected:(_)=>setState(()=>sel=id));})));}
  _open(s) async{final p=await SharedPreferences.getInstance();String sv=p.getString('server')??'';String u=p.getString('username')??'';String pw=p.getString('password')??'';final r=await http.get(Uri.parse('$sv/player_api.php?username=$u&password=$pw&action=get_series_info&series_id=${s['series_id']}'));final d=json.decode(r.body);final eps=d['episodes'];showDialog(context:context,builder:(_)=>AlertDialog(backgroundColor:Color(0xFF111111),title:Text(s['name'],style:TextStyle(color:Colors.white)),content:Container(width:500,height:450,child:ListView(children:eps.keys.map<Widget>((se)=>ExpansionTile(title:Text('الموسم $se',style:TextStyle(color:Colors.orange)),children:(eps[se] as List).map((e)=>ListTile(title:Text(e['title'],style:TextStyle(color:Colors.white)),onTap:(){Navigator.pop(context);String url='$sv/series/$u/$pw/${e['id']}.${e['container_extension']}';Navigator.push(context,MaterialPageRoute(builder:(_)=>PlayerScreen(url:url,title:e['title'])));})).toList())).toList()))));}
}
