name: Generate Release Keystore
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore kamelpro-release.jks -keyalg RSA -keysize 2048 -validity 10000 -alias kamelpro -storepass kamelpro123 -keypass kamelpro123 -dname "CN=KamelPro, OU=Dev, O=KamelPro, L=Tunis, S=Tunis, C=TN"
          base64 kamelpro-release.jks > keystore.txt
      
      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: kamelpro-release-keystore
          path: keystore.txt
