name: Build KAMEL PRO APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
      
      - name: Show pubspec version
        run: cat pubspec.yaml | grep version
      
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Get version from pubspec
        id: version
        run: echo "APP_VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f2 | cut -d '+' -f1)" >> $GITHUB_OUTPUT
        
      - name: Show APK version info
        run: |
          echo "### APK Version Info 👇" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ steps.version.outputs.APP_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "### SHA256 👇" >> $GITHUB_STEP_SUMMARY
          shasum -a 256 build/app/outputs/flutter-apk/app-release.apk >> $GITHUB_STEP_SUMMARY
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KAMEL-PRO-v${{ steps.version.outputs.APP_VERSION }}
          path: build/app/outputs/flutter-apk/app-release.apk
